version: '3'
services:
  fastdfs:
    image: sjqzhang/go-fastdfs
    container_name: fastdfs
    restart: always
    ports:
        - "8080:8080"
    command:
        - tracker
    volumes:
        - ./fastdfs_data:/data
    environment:
      - GO_FASTDFS_DIR=/data