version: '3'
services:
  fastdfs:
    image: sjqzhang/go-fastdfs
    container_name: go-fastdfs
    restart: always
    ports:
        - "8080:8080"
    volumes:
      - ./conf/cfg.json:/data/conf/cfg.json
      - ./fastdfs_data:/data
    environment:
      - GO_FASTDFS_DIR=/data