version: '3'
services:
  ubuntu:
    hostname: ubuntu
    image: ubuntu:latest
    container_name: ubuntu
    restart: always
    environment:
      - TZ=Asia/Shanghai # 设置容器时区与宿主机保持一致
    ports:
      - "10022:22"