version: '3'
services:
   RabbitMQ:
     container_name: RabbitMQ
     hostname: RabbitMQ
     image: rabbitmq:management
     restart: always
     ports:
       - "5672:5672"
       - "15672:15672"
     volumes:
       - ./rabbitmq:/var/lib/rabbitmq
     environment:
       - RABBITMQ_DEFAULT_USER=root
       - RABBITMQ_DEFAULT_PASS=e0BzbP90jwoSF!a9
       - RABBITMQ_DEFAULT_VHOST=default_vhost
       - TZ=Asia/Shanghai # 设置容器时区与宿主机保持一致