version: '3'
services:
  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - ./odoo-web-log:/var/log/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
  db:
    image: postgres:15
    restart: always
    container_name: postgres
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=e0BzbP90jwoSF!a9
    volumes:
      - ./odoo-db-data:/var/lib/postgresql/data