version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=e0BzbP90jwoSF!a9
  web:
    build: .
    # command: python odoo-bin --config=*.conf
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db