version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./logs:/var/log/nginx
      - ./conf.d:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/cert:/etc/nginx/cert
    environment:
     - TZ=Asia/Shanghai # 设置容器时区与宿主机保持一致
    privileged: true
