version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Shanghai # 设置容器时区与宿主机保持一致
    volumes:
      - ~/nginx/html:/usr/share/nginx/html
      - ~/nginx/static:/usr/share/nginx/static
      - ~/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/nginx/conf.d:/etc/nginx/conf.d
      - ~/nginx/cert:/etc/nginx/cert
      - ~/nginx/log:/var/log/nginx
