version: '3'
services:
  fdfs_tracker:
    image: delron/fastdfs
    container_name: fdfs_tracker
    restart: always
    ports:
        - "22122:22122"
    command:
        - tracker
    volumes:
        - ./tracker:/var/fdfs