version: '3'
services:
   redis:
    image: redis:7-alpine
    hostname: redis
    container_name: redis
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
       - "6379:6379"
    volumes:
       - ./data:/data
       - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M