version: '3'
services:
   redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    restart: always      
    environment:
      - TZ=Asia/Shanghai
    command: redis-server /etc/redis/redis.conf 
    privileged: true
    ports:
       - "6379:6379"
    volumes:
       - ./conf/redis.conf:/etc/redis/redis.conf
       - ./data:/data